domain: ""

image:
  repository: laynon/desafio
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: "128Mi"
    cpu: "500m"
  requests:
    memory: "64Mi"
    cpu: "250m"

replicaCount: 1

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix

labels:
  desafio: jackexperts
