apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jack-ingress
  labels:
    app: jack
    desafio: jackexperts
spec:
  rules:
    - host: desafio.jack  # m nome fictício para o dominio
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: desafio-service  # Nome real do seu serviço
                port:
                  number: 80
